% Fill in default parameters for the MaxEnt algorithm.
function algorithm_params = elirldefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    'seed',0,...
    'laplace_prior',0,...
    'all_features',1,...,
    'k', 2,...
    'mu', 1,...
    'muRatio',Inf,...
    'lambda',1,...
    'ridgeTerm',1,...
    'initializeWithFirstKTasks',false,...
    'lastFeatureIsABiasTerm',false,...
    'justEncode',false,...
    'task_id',1,...
    'hess_approx','use_cov');

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params,default_params);
