% Fill in default parameters for the MaxEnt algorithm.
function algorithm_params = elirlcddefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    'seed',0,...
    'laplace_prior',0,...
    'all_features',1,...,
    'k', 2,...
    'mu_1', 1,...
    'muRatio',Inf,...
    'mu_2',1,...
    'mu_3',1,...
    'ridgeTerm',1,...
    'initializeWithFirstKTasks',false,...
    'updateLMethod','blockCoordinate',...
    'updatePsiMethod','fullByLColumn',...
    'updatePsiWithOldL',false,...
    'lastFeatureIsABiasTerm',false,...
    'justEncode',false,...
    'numLPsiUpdates',1,...
    'task_id',1,...
    'group_id',1,...
    'hess_approx','use_cov');

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params,default_params);
