% Fill in default parameters for the gridworld example.
function mdp_params = synthetic_gridworlddefaultparams(mdp_params)

% Create default parameters.
default_params = struct(...
    'seed',0,...
    'n',32,...
    'b',4,...
    'determinism',1.0,...
    'discount',0.9,...
    'T',30,...
    'k',6);

% Set parameters.
mdp_params = filldefaultparams(mdp_params,default_params);
